### ISSUE TITLE
风扇控制

### ISSUE THREAD

**Issue by raffiagk** [alanleung2017/dell9020m-opencore0.6.5-bigsur-fan-control#1]
老哥，请教下，您的efi我借鉴了下，除了配置dell传感器还需要什么才能控制风扇转速

**Comment by alanleung2017** [comment]
> 老哥，请教下，您的efi我借鉴了下，除了配置dell传感器还需要什么才能控制风扇转速

你的配置方便给一下吗，就是加了dellsensor就行了，还有要下载一个软件macfancontrol

**Comment by alanleung2017** [comment]
> 老哥，请教下，您的efi我借鉴了下，除了配置dell传感器还需要什么才能控制风扇转速
config.plist需要有下面内容，我是通过opencore cofigure生成的配置文件
`
//搜索下面关键字
Contents/MacOS/SMCDellSensors	
`

**Comment by raffiagk** [comment]
> > 老哥，请教下，您的efi我借鉴了下，除了配置dell传感器还需要什么才能控制风扇转速
> 
> 你的配置方便给一下吗，就是加了dellsensor就行了，还有要下载一个软件macfancontrol

感谢回复，smcdellsensors 我已经加入，cpufan 转速显示出来了，但是调速 只能800 要么3200 调当中没有用，是否还有其他配置，或许是kext顺序不对？
